

spring:
  datasource:
    url: jdbc:mysql://${aws.db.url}/${aws.db.name}?autoReconnect=true&setTimezone=Asia/Seoul
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        show_sql: true
        format_sql: true
        use_sql_comments: true
        hbm2ddl:
          auto: create-drop
        default_batch_fetch_size: 1000

univcert:
  apikey: ${UNIVCERT_APIKEY}

---
auth:
  jwt:
    secretKey: ${JWT_SECRET_KEY}
    accessExp: 3600
    refreshExp: 592000
