

spring:
  datasource:
    url: jdbc:mysql://${aws.db.url}/${aws.db.name}?autoReconnect=true&setTimezone=Asia/Seoul
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        show_sql: true
        format_sql: true
        use_sql_comments: true
        hbm2ddl:
          auto: update
        default_batch_fetch_size: 1000
---
spring:
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}

univcert:
  apikey: ${UNIVCERT_APIKEY}

umark:
  mail:
    host: ${UMARK_MAIL_HOST}
    port: ${UMARK_MAIL_PORT}
    username: ${UMARK_MAIL_USERNAME}
    password: ${UMARK_MAIL_PASSWORD}

---
auth:
  jwt:
    secretKey: ${JWT_SECRET_KEY}
    accessExp: 3600
    refreshExp: 592000
